//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VergiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bakanlıklar
    {
        public int BakanlıkId { get; set; }
        public string bakanlıkName { get; set; }
        public string DaireBaskanlık { get; set; }
        public Nullable<decimal> Ciro { get; set; }
        public string Merkez { get; set; }
        public string Password { get; set; }
    }
}
