//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VergiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sikayet
    {
        public int SikayetId { get; set; }
        public Nullable<int> BakanlıkId { get; set; }
        public string TC { get; set; }
        public string Metin { get; set; }
        public string BakanlıkName { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
