//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VergiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vergiler
    {
        public int VergiId { get; set; }
        public string vergiName { get; set; }
        public string Tipi { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<int> Faiz { get; set; }
        public Nullable<int> KisiNo { get; set; }
        public Nullable<int> BakanlıkId { get; set; }
    }
}
